In [262]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import re

### 1) Write a python program to display IMDB’s Top rated 100 Indian movies’ data https://www.imdb.com/list/ls056092300/ (i.e. name, rating, year ofrelease) and make data frame.

In [378]:
#Get request sent to website-
page=requests.get('https://www.imdb.com/list/ls056092300/')
page

In [264]:
#BeautifulSoup object created- 
Soup=BeautifulSoup(page.content)

In [265]:
#Extracting movie name and year of release-
movie_details=[]
for i in Soup.find_all('h3',class_="lister-item-header"):
    movie_details.append(i.text)
movie_details

['\n1.\nShip of Theseus\n(2012)\n',
 '\n2.\nIruvar\n(1997)\n',
 '\n3.\nKaagaz Ke Phool\n(1959)\n',
 '\n4.\nLagaan: Once Upon a Time in India\n(2001)\n',
 '\n5.\nPather Panchali\n(1955)\n',
 '\n6.\nCharulata\n(1964)\n',
 '\n7.\nRang De Basanti\n(2006)\n',
 '\n8.\nDev.D\n(2009)\n',
 '\n9.\n3 Idiots\n(2009)\n',
 '\n10.\nAwaara\n(1951)\n',
 '\n11.\nNayakan\n(1987)\n',
 '\n12.\nAparajito\n(1956)\n',
 '\n13.\nPushpaka Vimana\n(1987)\n',
 '\n14.\nPyaasa\n(1957)\n',
 '\n15.\nGhatashraddha\n(1977)\n',
 '\n16.\nSholay\n(1975)\n',
 '\n17.\nAradhana\n(1969)\n',
 '\n18.\nDo Ankhen Barah Haath\n(1957)\n',
 '\n19.\nBombay\n(1995)\n',
 '\n20.\nNeecha Nagar\n(1946)\n',
 '\n21.\nDo Bigha Zamin\n(1953)\n',
 '\n22.\nGarm Hava\n(1974)\n',
 '\n23.\nPiravi\n(1989)\n',
 '\n24.\nMughal-E-Azam\n(1960)\n',
 '\n25.\nAmma Ariyan\n(1986)\n',
 '\n26.\nMadhumati\n(1958)\n',
 '\n27.\nGoopy Gyne Bagha Byne\n(1969)\n',
 '\n28.\nGangs of Wasseypur\n(2012)\n',
 '\n29.\nGuide\n(1965)\n',
 '\n30.\nSatya\n(1998)\n',
 '\n31.\nRoja\n(1992)\n',
 '\n32.\nMr. India\n(1987)\n',
 '\n33.\nThe Cloud-Capped Star\n(1960)\n',
 '\n34.\nHarishchandrachi Factory\n(2009)\n',
 '\n35.\nMasoom\n(1983)\n',
 '\n36.\nAgneepath\n(1990)\n',
 '\n37.\nTabarana Kathe\n(1986)\n',
 '\n38.\nZakhm\n(1998)\n',
 '\n39.\nDil Chahta Hai\n(2001)\n',
 '\n40.\nBhaag Milkha Bhaag\n(2013)\n',
 '\n41.\nChupke Chupke\n(1975)\n',
 '\n42.\nDilwale Dulhania Le Jayenge\n(1995)\n',
 '\n43.\nTaare Zameen Par\n(2007)\n',
 '\n44.\nArdh Satya\n(1983)\n',
 '\n45.\nBhumika\n(1977)\n',
 '\n46.\nEnthiran\n(2010)\n',
 '\n47.\nSadma\n(1983)\n',
 '\n48.\nShwaas\n(2004)\n',
 '\n49.\nLamhe\n(1991)\n',
 '\n50.\nHaqeeqat\n(1964)\n',
 '\n51.\nShree 420\n(1955)\n',
 '\n52.\nKannathil Muthamittal\n(2002)\n',
 '\n53.\nHum Aapke Hain Koun..!\n(1994)\n',
 '\n54.\nUstad Hotel\n(2012)\n',
 '\n55.\nBandit Queen\n(1994)\n',
 '\n56.\nLakshya\n(2004)\n',
 '\n57.\nBlack Friday\n(2004)\n',
 '\n58.\nManthan\n(1976)\n',
 '\n59.\nApoorva Raagangal\n(1975)\n',
 '\n60.\nEnglish Vinglish\n(2012)\n',
 '\n61.\nJewel Thief\n(1967)\n',
 '\n62.\nPakeezah\n(1972)\n',
 '\n63.\nMaqbool\n(2003)\n',
 '\n64.\nJis Desh Men Ganga Behti Hai\n(1960)\n',
 '\n65.\nSahib Bibi Aur Ghulam\n(1962)\n',
 '\n66.\nShatranj Ke Khilari\n(1977)\n',
 '\n67.\nNarthanasala\n(1963)\n',
 '\n68.\nChandni Bar\n(2001)\n',
 '\n69.\nVaaranam Aayiram\n(2008)\n',
 '\n70.\nMr. and Mrs. Iyer\n(2002)\n',
 '\n71.\nChandni\n(1989)\n',
 '\n72.\nEnglish, August\n(1994)\n',
 '\n73.\nCelluloid\n(2013)\n',
 '\n74.\nSagara Sangamam\n(1983)\n',
 '\n75.\nMunna Bhai M.B.B.S.\n(2003)\n',
 '\n76.\nSaaransh\n(1984)\n',
 '\n77.\nGuddi\n(1971)\n',
 '\n78.\nVanaja\n(2006)\n',
 '\n79.\nVazhakku Enn 18/9\n(2012)\n',
 '\n80.\nGangaajal\n(2003)\n',
 '\n81.\nAngoor\n(1982)\n',
 '\n82.\nGuru\n(2007)\n',
 '\n83.\nAndaz Apna Apna\n(1994)\n',
 '\n84.\nSangam\n(I) (1964)\n',
 '\n85.\nOka Oori Katha\n(1978)\n',
 '\n86.\nBhuvan Shome\n(1969)\n',
 '\n87.\nBorder\n(I) (1997)\n',
 '\n88.\nParineeta\n(2005)\n',
 '\n89.\nDevdas\n(1955)\n',
 '\n90.\nAbohomaan\n(2009)\n',
 '\n91.\nKuch Kuch Hota Hai\n(1998)\n',
 '\n92.\nPithamagan\n(2003)\n',
 '\n93.\nVeyyil\n(2006)\n',
 '\n94.\nChemmeen\n(1965)\n',
 '\n95.\nJaane Bhi Do Yaaro\n(1983)\n',
 '\n96.\nApur Sansar\n(1959)\n',
 '\n97.\nKanchivaram\n(2008)\n',
 '\n98.\nMonsoon Wedding\n(2001)\n',
 '\n99.\nBlack\n(2005)\n',
 '\n100.\nDeewaar\n(1975)\n']

In [266]:
#Extracting movie ratings-
ratings=[]
for i in Soup.find_all('div',class_="ipl-rating-star small"):
    ratings.append(i.text)
ratings

['\n\n\n\n\n\n\n\n8\n',
 '\n\n\n\n\n\n\n\n8.4\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.9\n',
 '\n\n\n\n\n\n\n\n8.4\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.6\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n8.6\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n7.6\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.6\n',
 '\n\n\n\n\n\n\n\n8.4\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n6.6\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n8\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.4\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.7\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.7\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.4\n',
 '\n\n\n\n\n\n\n\n8.4\n',
 '\n\n\n\n\n\n\n\n7.6\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.9\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n8\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.4\n',
 '\n\n\n\n\n\n\n\n7.1\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n7.2\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n7.9\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n7.5\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n7.5\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.4\n',
 '\n\n\n\n\n\n\n\n7.6\n',
 '\n\n\n\n\n\n\n\n7.6\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n7.9\n',
 '\n\n\n\n\n\n\n\n7.2\n',
 '\n\n\n\n\n\n\n\n8\n',
 '\n\n\n\n\n\n\n\n7.1\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.5\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.6\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n7.9\n',
 '\n\n\n\n\n\n\n\n6.7\n',
 '\n\n\n\n\n\n\n\n7.7\n',
 '\n\n\n\n\n\n\n\n7.7\n',
 '\n\n\n\n\n\n\n\n8.8\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n7.2\n',
 '\n\n\n\n\n\n\n\n7.2\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n7.7\n',
 '\n\n\n\n\n\n\n\n8\n',
 '\n\n\n\n\n\n\n\n7.3\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n7.2\n',
 '\n\n\n\n\n\n\n\n7.9\n',
 '\n\n\n\n\n\n\n\n7.2\n',
 '\n\n\n\n\n\n\n\n7.7\n',
 '\n\n\n\n\n\n\n\n7.5\n',
 '\n\n\n\n\n\n\n\n7.5\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n7.9\n',
 '\n\n\n\n\n\n\n\n7.8\n',
 '\n\n\n\n\n\n\n\n8.3\n',
 '\n\n\n\n\n\n\n\n8.4\n',
 '\n\n\n\n\n\n\n\n8.2\n',
 '\n\n\n\n\n\n\n\n7.3\n',
 '\n\n\n\n\n\n\n\n8.1\n',
 '\n\n\n\n\n\n\n\n8\n']

In [267]:
#Creating dataframe-
df=pd.DataFrame({'Movie_details':movie_details,'Ratings':ratings})
df

                                        Movie_details                Ratings
0                     \n1.\nShip of Theseus\n(2012)\n    \n\n\n\n\n\n\n\n8\n
1                              \n2.\nIruvar\n(1997)\n  \n\n\n\n\n\n\n\n8.4\n
2                     \n3.\nKaagaz Ke Phool\n(1959)\n  \n\n\n\n\n\n\n\n7.8\n
3   \n4.\nLagaan: Once Upon a Time in India\n(2001)\n  \n\n\n\n\n\n\n\n8.1\n
4                     \n5.\nPather Panchali\n(1955)\n  \n\n\n\n\n\n\n\n8.2\n
..                                                ...                    ...
95                       \n96.\nApur Sansar\n(1959)\n  \n\n\n\n\n\n\n\n8.4\n
96                       \n97.\nKanchivaram\n(2008)\n  \n\n\n\n\n\n\n\n8.2\n
97                   \n98.\nMonsoon Wedding\n(2001)\n  \n\n\n\n\n\n\n\n7.3\n
98                             \n99.\nBlack\n(2005)\n  \n\n\n\n\n\n\n\n8.1\n
99                          \n100.\nDeewaar\n(1975)\n    \n\n\n\n\n\n\n\n8\n

[100 rows x 2 columns]

In [268]:
#Cleaning data-
df['Movie_details']=df['Movie_details'].str.replace('\n+','',regex=True)
df['Ratings']=df['Ratings'].str.replace('\n+','',regex=True)
df

                                Movie_details Ratings
0                     1.Ship of Theseus(2012)       8
1                              2.Iruvar(1997)     8.4
2                     3.Kaagaz Ke Phool(1959)     7.8
3   4.Lagaan: Once Upon a Time in India(2001)     8.1
4                     5.Pather Panchali(1955)     8.2
..                                        ...     ...
95                       96.Apur Sansar(1959)     8.4
96                       97.Kanchivaram(2008)     8.2
97                   98.Monsoon Wedding(2001)     7.3
98                             99.Black(2005)     8.1
99                          100.Deewaar(1975)       8

[100 rows x 2 columns]

In [269]:
df['Movie_name']=df['Movie_details'].str.split('(').str.get(0).str.replace('\d.','',regex=True)
df['Year']=df['Movie_details'].str.split('(').str.get(1).str.replace(')','',regex=True)
df

,Movie_details,Ratings,Movie_name,Year
0,1.Ship of Theseus(2012),8,Ship of Theseus,2012
1,2.Iruvar(1997),8.4,Iruvar,1997
2,3.Kaagaz Ke Phool(1959),7.8,Kaagaz Ke Phool,1959
3,4.Lagaan: Once Upon a Time in India(2001),8.1,Lagaan: Once Upon a Time in India,2001
4,5.Pather Panchali(1955),8.2,Pather Panchali,1955
...,...,...,...,...
95,96.Apur Sansar(1959),8.4,.Apur Sansar,1959
96,97.Kanchivaram(2008),8.2,.Kanchivaram,2008
97,98.Monsoon Wedding(2001),7.3,.Monsoon Wedding,2001
98,99.Black(2005),8.1,.Black,2005
99,100.Deewaar(1975),8,Deewaar,1975

In [270]:
df=df.drop('Movie_details',axis=1)

In [271]:
c1=df['Movie_name']
df.insert(0,'Name',c1)

In [272]:
df

,Name,Ratings,Movie_name,Year
0,Ship of Theseus,8,Ship of Theseus,2012
1,Iruvar,8.4,Iruvar,1997
2,Kaagaz Ke Phool,7.8,Kaagaz Ke Phool,1959
3,Lagaan: Once Upon a Time in India,8.1,Lagaan: Once Upon a Time in India,2001
4,Pather Panchali,8.2,Pather Panchali,1955
...,...,...,...,...
95,.Apur Sansar,8.4,.Apur Sansar,1959
96,.Kanchivaram,8.2,.Kanchivaram,2008
97,.Monsoon Wedding,7.3,.Monsoon Wedding,2001
98,.Black,8.1,.Black,2005
99,Deewaar,8,Deewaar,1975

In [273]:
df=df.drop('Movie_name',axis=1)
df

                                 Name Ratings  Year
0                     Ship of Theseus       8  2012
1                              Iruvar     8.4  1997
2                     Kaagaz Ke Phool     7.8  1959
3   Lagaan: Once Upon a Time in India     8.1  2001
4                     Pather Panchali     8.2  1955
..                                ...     ...   ...
95                       .Apur Sansar     8.4  1959
96                       .Kanchivaram     8.2  2008
97                   .Monsoon Wedding     7.3  2001
98                             .Black     8.1  2005
99                            Deewaar       8  1975

[100 rows x 3 columns]

### 5) Write a python program to scrape house details from mentioned URL. It should include house title, location, area, EMI and price from https://www.nobroker.in/ .Enter three localities which are Indira Nagar, Jayanagar, Rajaji Nagar.

In [280]:
#Get request sent to website
page5=requests.get('https://www.nobroker.in/property/sale/bangalore/multiple?searchParam=W3sibGF0IjoxMi45NzgzNjkyLCJsb24iOjc3LjY0MDgzNTYsInBsYWNlSWQiOiJDaElKa1FOM0dLUVdyanNSTmhCUUpyaEdEN1UiLCJwbGFjZU5hbWUiOiJJbmRpcmFuYWdhciJ9LHsibGF0IjoxMi45MzA3NzM1LCJsb24iOjc3LjU4MzgzMDIsInBsYWNlSWQiOiJDaElKMmRkbFo1Z1ZyanNSaDFCT0FhZi1vcnMiLCJwbGFjZU5hbWUiOiJKYXlhbmFnYXIifSx7ImxhdCI6MTIuOTk4MTczMiwibG9uIjo3Ny41NTMwNDQ1OTk5OTk5OSwicGxhY2VJZCI6IkNoSUp4Zlc0RFBNOXJqc1JLc05URy01cF9RUSIsInBsYWNlTmFtZSI6IlJhamFqaW5hZ2FyIn1d&radius=2.0&city=bangalore&locality=Indiranagar,Jayanagar,Rajajinagar')
page5

In [281]:
#Creating BeautifulSoup Object
soup5=BeautifulSoup(page5.content)

In [282]:
#Extracting titles
titles=[]
for i in soup5.find_all('a',class_="overflow-hidden overflow-ellipsis whitespace-nowrap max-w-80pe po:max-w-full"):
    titles.append(i.text)
titles

['2 BHK Apartment In Alpine Regency For Sale  In Jayanagar',
 '4 BHK House For Sale  In Rajajinagar',
 '4+ BHK House For Sale  In Jayanagar',
 '3 BHK Apartment In Amarjyothi Apartments For Sale  In Jayanagar 6th Block, Jayanagar',
 '4 BHK Flat In Brigade Gateway Complex For Sale  In Rajaji Nagar',
 '4 BHK Flat In Apartment For Sale  In Rajajinagar',
 '3 BHK House For Sale  In Veeresh Cinemas',
 '3 BHK Flat In Santa Clara Apartment For Sale  In Marenahalli, Jayanagar',
 '2 BHK Flat In Pallava Terrace Apartments For Sale  In Pallava Terrace, Tata Silk Farm, Jayanagar, Bengaluru, Karnataka 560070, India',
 '4+ BHK House For Sale  In  Rajajinagar',
 '3 BHK Flat In Nilavu  For Sale  In Indiranagar',
 '3 BHK House For Sale  In Jayanagar 9th Block',
 '3 BHK Apartment In Lodha Azur For Sale near Jayanagar',
 '3 BHK Flat In Parasmani Regency For Sale  In Jayanagar',
 '2 BHK Flat In Shanthi Park Apartments For Sale  In Jayanagar 9th Block',
 '2 BHK Apartment In Gopalan Admirality Court, Indiranagar For Sale  In Indiranagar',
 '3 BHK House For Sale  In Jayanagar',
 '4 BHK Apartment In Codename Indiranagar For Sale  In Indiranagar',
 '3 BHK Apartment In Codename Indiranagar For Sale  In Indiranagar',
 '3 BHK Apartment In Jayanagar Residency For Sale  In Jayanagar',
 '4+ BHK House For Sale  In Jayanagar',
 '2 BHK Flat In Bindi Sundar Residency For Sale  In Rajajinagar',
 '3 BHK Flat In Ltg Sr Grand For Sale  In Rajaji Nagar',
 '2 BHK Flat In Jayanagar Residency For Sale  In Jayanagar 3rd Block ',
 '3 BHK Flat In Sri Maruthi For Sale  In Jayanagar',
 '2 BHK Apartment In Alpine Regency For Sale  In Jayanagar']

In [283]:
#Extracting location
location=[]
for i in soup5.find_all('div',class_="mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95"):
    location.append(i.text)
location

['Alpine Regency\xa0  Alpine Regency, 10th D Main Rd, 1st Block, Jaya Nagar East, Jayanagar, Bengaluru, Karnataka 560011, India',
 "Independent House, Mahakavi Kuvempu Rd Maruthi Extension,Near Malgudi's Donne Biriyani",
 'Independent House, Tilak Nagar, near S.K. Bakery',
 'Amarjyothi Apartments\xa0 Jayanagar 6th block, Bangalore',
 '26/1, 80 Feet Road, Dr. Rajkumar Road, Rajaji Nagar, Bangalore',
 'mahakavi kuvempu road, Near Mahakavi Kuvempu metro station',
 'Independent House, 4th Cross Road Agrahaara Dasarahalli Maagadi Main Road nearShell Petrolstation',
 '3Rd Cross Rd18th main, 9th Block, Marenahalli',
 '17 north main yediyur behind samudaya bhavan bangalore-560070',
 "Independent House, 80 Feet Rd 6th Block, near St. Ann's High School",
 'Indira Nagar II Stage, Hoysala Nagar, Near BDA Complex',
 'Independent House, 125a, 38th B Cross Road, near MK Ahemad Bazar',
 'Lodha Azur\xa0 Akshay Nagar,Bangalore',
 'behind Southend metro ',
 'Shanthi Park Apartments, Kottapalya, Jayanagara 9th Block, Jayanagar, Bengaluru, Karnataka, India',
 'Gopalan Admirality Court, Indiranagar\xa0  6th Main Rd, Eshwara Layout, Indiranagar, Bengaluru, Karnataka 560038, India',
 'Independent House,  9th Block,Near  MEWA - VANGUARD BUSINESS SCHOOL',
 'Codename Indiranagar\xa0 Indiranagar, Bangalore.',
 'Codename Indiranagar\xa0 Indiranagar, Bangalore.',
 'Jayanagar Residency\xa0 Jayanagar  Jayanagar Residency',
 'Independent House, No:1,First cross street,RBI colony.Tilak nagar police station',
 '72nd Cross Rd, 5th Block, Jedara Halli, Rajajinagar, Bengaluru, Karnataka 560023, India',
 'west of card road near modi hospital ',
 'jayanager residency. near D mart, Jayanager 3rd block East,',
 'Indira Gandhi Institute Of Child Health 1st Block, Jayanagar, Bengaluru, Karnataka 560029, India',
 'Alpine Regency\xa0  Alpine Regency, 10th D Main Rd, 1st Block, Jaya Nagar East, Jayanagar, Bengaluru, Karnataka 560011, India']

In [284]:
#Extracting price, EMI and area.
data=[]
for i in soup5.find_all('div', class_="font-semi-bold heading-6"):
    data.append(i.text)
data

['₹1.65 Crores',
 '₹94,568/Month',
 '1,320 sqft',
 '₹1.1 Crores',
 '₹63,045/Month',
 '2,000 sqft',
 '₹2.5 Crores',
 '₹1.43 Lacs/Month',
 '2,500 sqft',
 '₹1.8 Crores',
 '₹1.03 Lacs/Month',
 '1,552 sqft',
 '₹4.2 Crores',
 '₹2.41 Lacs/Month',
 '2,360 sqft',
 '₹1.8 Crores',
 '₹1.03 Lacs/Month',
 '2,055 sqft',
 '₹1.45 Crores',
 '₹83,106/Month',
 '2,400 sqft',
 '₹1.15 Crores',
 '₹65,911/Month',
 '1,395 sqft',
 '₹1 Crore',
 '₹57,314/Month',
 '1,050 sqft',
 '₹1.25 Crores',
 '₹71,643/Month',
 '2,400 sqft',
 '₹2.99 Crores',
 '₹1.71 Lacs/Month',
 '1,600 sqft',
 '₹1.45 Crores',
 '₹83,106/Month',
 '1,400 sqft',
 '₹2.25 Crores',
 '₹1.29 Lacs/Month',
 '1,710 sqft',
 '₹2.77 Crores',
 '₹1.59 Lacs/Month',
 '1,959 sqft',
 '₹95 Lacs',
 '₹54,448/Month',
 '1,100 sqft',
 '₹1.8 Crores',
 '₹1.03 Lacs/Month',
 '1,360 sqft',
 '₹8.95 Crores',
 '₹5.13 Lacs/Month',
 '1,200 sqft',
 '₹6 Crores',
 '₹3.44 Lacs/Month',
 '2,600 sqft',
 '₹5.6 Crores',
 '₹3.21 Lacs/Month',
 '2,000 sqft',
 '₹2.25 Crores',
 '₹1.29 Lacs/Month',
 '2,000 sqft',
 '₹7 Crores',
 '₹4.01 Lacs/Month',
 '4,000 sqft',
 '₹70 Lacs',
 '₹40,120/Month',
 '896 sqft',
 '₹2.3 Crores',
 '₹1.32 Lacs/Month',
 '1,865 sqft',
 '₹1.4 Crores',
 '₹80,240/Month',
 '1,167 sqft',
 '₹1.2 Crores',
 '₹68,777/Month',
 '1,400 sqft',
 '₹1.65 Crores',
 '₹94,568/Month',
 '1,320 sqft']

In [285]:
#Sublisting the data to distribute it into 3 columns
sublist=[data[i:i+3] for i in range(0,len(data),3)]

In [286]:
sublist

[['₹1.65 Crores', '₹94,568/Month', '1,320 sqft'],
 ['₹1.1 Crores', '₹63,045/Month', '2,000 sqft'],
 ['₹2.5 Crores', '₹1.43 Lacs/Month', '2,500 sqft'],
 ['₹1.8 Crores', '₹1.03 Lacs/Month', '1,552 sqft'],
 ['₹4.2 Crores', '₹2.41 Lacs/Month', '2,360 sqft'],
 ['₹1.8 Crores', '₹1.03 Lacs/Month', '2,055 sqft'],
 ['₹1.45 Crores', '₹83,106/Month', '2,400 sqft'],
 ['₹1.15 Crores', '₹65,911/Month', '1,395 sqft'],
 ['₹1 Crore', '₹57,314/Month', '1,050 sqft'],
 ['₹1.25 Crores', '₹71,643/Month', '2,400 sqft'],
 ['₹2.99 Crores', '₹1.71 Lacs/Month', '1,600 sqft'],
 ['₹1.45 Crores', '₹83,106/Month', '1,400 sqft'],
 ['₹2.25 Crores', '₹1.29 Lacs/Month', '1,710 sqft'],
 ['₹2.77 Crores', '₹1.59 Lacs/Month', '1,959 sqft'],
 ['₹95 Lacs', '₹54,448/Month', '1,100 sqft'],
 ['₹1.8 Crores', '₹1.03 Lacs/Month', '1,360 sqft'],
 ['₹8.95 Crores', '₹5.13 Lacs/Month', '1,200 sqft'],
 ['₹6 Crores', '₹3.44 Lacs/Month', '2,600 sqft'],
 ['₹5.6 Crores', '₹3.21 Lacs/Month', '2,000 sqft'],
 ['₹2.25 Crores', '₹1.29 Lacs/Month', '2,000 sqft'],
 ['₹7 Crores', '₹4.01 Lacs/Month', '4,000 sqft'],
 ['₹70 Lacs', '₹40,120/Month', '896 sqft'],
 ['₹2.3 Crores', '₹1.32 Lacs/Month', '1,865 sqft'],
 ['₹1.4 Crores', '₹80,240/Month', '1,167 sqft'],
 ['₹1.2 Crores', '₹68,777/Month', '1,400 sqft'],
 ['₹1.65 Crores', '₹94,568/Month', '1,320 sqft']]

In [287]:
#Creating a dataframe as per the requirement
df=pd.DataFrame({'Title':titles,'Location':location,'Price':[item[0] for item in sublist],'EMI':[item[1] for item in sublist],'Area':[item[2] for item in sublist]})
df

,Title,Location,Price,EMI,Area
0,2 BHK Apartment In Alpine Regency For Sale In...,"Alpine Regency Alpine Regency, 10th D Main R...",₹1.65 Crores,"₹94,568/Month","1,320 sqft"
1,4 BHK House For Sale In Rajajinagar,"Independent House, Mahakavi Kuvempu Rd Maruthi...",₹1.1 Crores,"₹63,045/Month","2,000 sqft"
2,4+ BHK House For Sale In Jayanagar,"Independent House, Tilak Nagar, near S.K. Bakery",₹2.5 Crores,₹1.43 Lacs/Month,"2,500 sqft"
3,3 BHK Apartment In Amarjyothi Apartments For S...,"Amarjyothi Apartments Jayanagar 6th block, Ba...",₹1.8 Crores,₹1.03 Lacs/Month,"1,552 sqft"
4,4 BHK Flat In Brigade Gateway Complex For Sale...,"26/1, 80 Feet Road, Dr. Rajkumar Road, Rajaji ...",₹4.2 Crores,₹2.41 Lacs/Month,"2,360 sqft"
5,4 BHK Flat In Apartment For Sale In Rajajinagar,"mahakavi kuvempu road, Near Mahakavi Kuvempu m...",₹1.8 Crores,₹1.03 Lacs/Month,"2,055 sqft"
6,3 BHK House For Sale In Veeresh Cinemas,"Independent House, 4th Cross Road Agrahaara Da...",₹1.45 Crores,"₹83,106/Month","2,400 sqft"
7,3 BHK Flat In Santa Clara Apartment For Sale ...,"3Rd Cross Rd18th main, 9th Block, Marenahalli",₹1.15 Crores,"₹65,911/Month","1,395 sqft"
8,2 BHK Flat In Pallava Terrace Apartments For S...,17 north main yediyur behind samudaya bhavan b...,₹1 Crore,"₹57,314/Month","1,050 sqft"
9,4+ BHK House For Sale In Rajajinagar,"Independent House, 80 Feet Rd 6th Block, near ...",₹1.25 Crores,"₹71,643/Month","2,400 sqft"
10,3 BHK Flat In Nilavu For Sale In Indiranagar,"Indira Nagar II Stage, Hoysala Nagar, Near BDA...",₹2.99 Crores,₹1.71 Lacs/Month,"1,600 sqft"
11,3 BHK House For Sale In Jayanagar 9th Block,"Independent House, 125a, 38th B Cross Road, ne...",₹1.45 Crores,"₹83,106/Month","1,400 sqft"
12,3 BHK Apartment In Lodha Azur For Sale near Ja...,"Lodha Azur Akshay Nagar,Bangalore",₹2.25 Crores,₹1.29 Lacs/Month,"1,710 sqft"
13,3 BHK Flat In Parasmani Regency For Sale In J...,behind Southend metro,₹2.77 Crores,₹1.59 Lacs/Month,"1,959 sqft"
14,2 BHK Flat In Shanthi Park Apartments For Sale...,"Shanthi Park Apartments, Kottapalya, Jayanagar...",₹95 Lacs,"₹54,448/Month","1,100 sqft"
15,"2 BHK Apartment In Gopalan Admirality Court, I...","Gopalan Admirality Court, Indiranagar 6th Ma...",₹1.8 Crores,₹1.03 Lacs/Month,"1,360 sqft"
16,3 BHK House For Sale In Jayanagar,"Independent House, 9th Block,Near MEWA - VAN...",₹8.95 Crores,₹5.13 Lacs/Month,"1,200 sqft"
17,4 BHK Apartment In Codename Indiranagar For Sa...,"Codename Indiranagar Indiranagar, Bangalore.",₹6 Crores,₹3.44 Lacs/Month,"2,600 sqft"
18,3 BHK Apartment In Codename Indiranagar For Sa...,"Codename Indiranagar Indiranagar, Bangalore.",₹5.6 Crores,₹3.21 Lacs/Month,"2,000 sqft"
19,3 BHK Apartment In Jayanagar Residency For Sal...,Jayanagar Residency Jayanagar Jayanagar Resi...,₹2.25 Crores,₹1.29 Lacs/Month,"2,000 sqft"
20,4+ BHK House For Sale In Jayanagar,"Independent House, No:1,First cross street,RBI...",₹7 Crores,₹4.01 Lacs/Month,"4,000 sqft"
21,2 BHK Flat In Bindi Sundar Residency For Sale ...,"72nd Cross Rd, 5th Block, Jedara Halli, Rajaji...",₹70 Lacs,"₹40,120/Month",896 sqft
22,3 BHK Flat In Ltg Sr Grand For Sale In Rajaji...,west of card road near modi hospital,₹2.3 Crores,₹1.32 Lacs/Month,"1,865 sqft"
23,2 BHK Flat In Jayanagar Residency For Sale In...,"jayanager residency. near D mart, Jayanager 3r...",₹1.4 Crores,"₹80,240/Month","1,167 sqft"
24,3 BHK Flat In Sri Maruthi For Sale In Jayanagar,Indira Gandhi Institute Of Child Health 1st Bl...,₹1.2 Crores,"₹68,777/Month","1,400 sqft"
25,2 BHK Apartment In Alpine Regency For Sale In...,"Alpine Regency Alpine Regency, 10th D Main R...",₹1.65 Crores,"₹94,568/Month","1,320 sqft"

### 6) Write a python program to scrape first 10 product details which include product name , price , Image URL from https://www.bewakoof.com/bestseller?sort=popular .

In [288]:
#Get request sent to website
page6=requests.get('https://www.bewakoof.com/bestseller?sort=popular')
page6

In [289]:
#Creating BeautifulSoup object
soup6=BeautifulSoup(page6.content)

In [290]:
#Exracting product name-
p_name=[]
for i in soup6.find_all('h2',class_="clr-shade4 h3-p-name undefined false")[:10]:
    p_name.append(i.text)
p_name

["Women's Pink & White Camo Printed Oversized Short Top",
 "Women's White Bored Typography Oversized Short Top",
 "Women's White & Black All Over Mickey Printed Oversized Short Top",
 "Women's White All Over Tweety Printed Oversized Short Top",
 "Women's Black All Over Printed Oversized Short Top",
 "Women's White MOTD Panda Graphic Printed T-shirt",
 "Women's Black No We in Food Graphic Printed Boyfriend T-shirt",
 "Women's Black Fragile Graphic Printed Boyfriend T-shirt",
 "Men's Black I Need Some Space Teddy Graphic Printed Oversized T-shirt",
 "Men's Red Moon Rider Graphic Printed Oversized T-shirt"]

In [291]:
#Exracting product price-
price=[]
for i in soup6.find_all('div',class_="discountedPriceText clr-p-black false")[:10]:
    price.append(i.text)
price

['₹599',
 '₹549',
 '₹379',
 '₹499',
 '₹399',
 '₹369',
 '₹399',
 '₹399',
 '₹549',
 '₹749']

In [292]:
#Exracting image url-
image_url=[]
for i in soup6.find_all('img',class_="productImgTag")[:10]:
    image_url.append(i['src'])
image_url

['https://images.bewakoof.com/t640/women-s-pink-white-camo-printed-oversized-t-shirt-580369-1686301190-1.jpg',
 'https://images.bewakoof.com/t640/women-white-printed-top-26-582038-1689082446-1.jpg',
 'https://images.bewakoof.com/t640/women-s-white-oversized-t-shirt-584434-1684230405-1.jpg',
 'https://images.bewakoof.com/t640/women-aop-oversize-t-shirt-2-580367-1685446636-1.jpg',
 'https://images.bewakoof.com/t640/women-aop-oversize-t-shirt-3-580366-1682421809-1.JPG',
 'https://images.bewakoof.com/t640/women-s-white-motd-panda-t-shirt-479771-1655815714-1.jpg',
 'https://images.bewakoof.com/t640/women-s-black-no-we-in-food-graphic-printed-boyfriend-t-shirt-483824-1656155113-1.jpg',
 'https://images.bewakoof.com/t640/fragile-boyfriend-t-shirt-516553-1657179813-1.jpg',
 'https://images.bewakoof.com/t640/men-s-black-i-need-some-space-teddy-graphic-printed-oversized-t-shirt-502010-1709216996-1.jpg',
 'https://images.bewakoof.com/t640/men-s-red-moon-rider-graphic-printed-oversized-t-shirt-502017-1701423884-1.jpg']

In [293]:
#Creating Dataframe-
df6=pd.DataFrame({'Product name':p_name,'Price':price,'Image URL':image_url})
df6

,Product name,Price,Image URL
0,Women's Pink & White Camo Printed Oversized Sh...,₹599,https://images.bewakoof.com/t640/women-s-pink-...
1,Women's White Bored Typography Oversized Short...,₹549,https://images.bewakoof.com/t640/women-white-p...
2,Women's White & Black All Over Mickey Printed ...,₹379,https://images.bewakoof.com/t640/women-s-white...
3,Women's White All Over Tweety Printed Oversize...,₹499,https://images.bewakoof.com/t640/women-aop-ove...
4,Women's Black All Over Printed Oversized Short...,₹399,https://images.bewakoof.com/t640/women-aop-ove...
5,Women's White MOTD Panda Graphic Printed T-shirt,₹369,https://images.bewakoof.com/t640/women-s-white...
6,Women's Black No We in Food Graphic Printed Bo...,₹399,https://images.bewakoof.com/t640/women-s-black...
7,Women's Black Fragile Graphic Printed Boyfrien...,₹399,https://images.bewakoof.com/t640/fragile-boyfr...
8,Men's Black I Need Some Space Teddy Graphic Pr...,₹549,https://images.bewakoof.com/t640/men-s-black-i...
9,Men's Red Moon Rider Graphic Printed Oversized...,₹749,https://images.bewakoof.com/t640/men-s-red-moo...

### 7) Please visit https://www.cnbc.com/world/?region=world and scrap- a) headings b) date c) News link

In [294]:
#Get request sent to website-
page7=requests.get('https://www.cnbc.com/world/?region=world')
page7

In [295]:
#Creating BeautifulSoup object-
soup7=BeautifulSoup(page7.content)

In [307]:
# Extracting news hadings-
headings = []
for i in soup7.find_all('a',class_="Card-title"):
    headings.append(i.text)
headings

['Wall Street could be in for another good quarter after an exuberant start to the year, history shows',
 'S&P 500 closes at a fresh record, posts strongest first-quarter performance since 2019: Live updates',
 'The S&P 500 is about to wrap the quarter with a 10% gain. Resist the urge to time a pullback',
 'How this bull market could unravel and what to watch for, according to Larry McDonald',
 'This winning sector could see even more upside once the Fed starts cutting rates',
 'Morgan Stanley names its top picks for the catch-up trade in energy',
 "Investors focused 'overwhelmingly' on bitcoin over other crypto, says BlackRock",
 '‘The frenzy continues’: Researcher names signs of an AI bubble amid Nvidia hype',
 'Wall Street could see another good quarter after strong start to 2024',
 'Russia launches barrage of 99 drones and missiles on Ukraine’s energy system, officials say',
 "Russia knew of terrorist attack plot weeks ago: Ukraine's military spy chief",
 "Putin says NATO won't be attacked but F-16s will; Kyiv claims Russia knew terror attack was coming",
 'Russia claims the West, Kyiv ordered the Moscow massacre. Now it has to prove it',
 "Russia says it's 'hard to believe' Islamic State group behind terror attack; death toll rises to 140",
 "Nikolaj Coster-Waldau on the UN’s 'Weather Kids' climate action campaign",
 'Hopes for buried hydrogen’s clean energy potential triggers a global gold rush',
 'Earth on the brink of critical warming threshold after a ‘chart-busting’ year',
 'Modular construction, seen as a solution to housing crises, is failing to take off',
 'Paris has hiked parking charges on SUVs. Now cities like London are taking note',
 "Italy's new 'Orient Express' isn't running yet — but rates are already soaring",
 "A new Japanese restaurant tops 'Asia's 50 Best Restaurants' list",
 "'Quiet luxury' was once about fashion, but now it's how the top 1% travel too",
 'Passport-free travel in Singapore is here — but only for certain travelers',
 "Japan launches bullet train service to a region that 'guidebooks rarely mention'",
 'California, not Florida, is home to the richest retirement towns in the U.S.',
 'Just 1% of construction CEOs are women—how this 30-year-old became one of them',
 "How a 36-year-old with 'little experience' built a $2 billion marketing company",
 '10 in-demand remote jobs paying over $100,000 that companies are hiring for now',
 'The ultimate guide to earning passive income online',
 'eVTOLS: How flying cars are becoming reality',
 "How China's property bubble burst",
 'What is the World Economic Forum?',
 'The Quad is going beyond military exercises — and China is watching',
 'Why a coup in Guinea was felt around the world']

In [323]:
# Extracting news link-
link = []
for i in soup7.find_all('a',class_="Card-title"):
    link.append(i['href'])
link

['https://www.cnbc.com/2024/03/28/wall-street-could-see-another-good-quarter-after-strong-start-to-2024.html',
 'https://www.cnbc.com/2024/03/27/stock-market-today-live-updates.html',
 'https://www.cnbc.com/2024/03/28/the-sp-500-is-about-to-wrap-the-quarter-with-a-10percent-gain-resist-the-urge-to-time-a-pullback.html',
 'https://www.cnbc.com/2024/03/28/how-this-bull-market-could-unravel-and-what-to-watch-for-according-to-larry-mcdonald.html',
 'https://www.cnbc.com/2024/03/29/this-sector-notching-new-highs-should-benefit-from-fed-rate-cuts.html',
 'https://www.cnbc.com/2024/03/29/morgan-stanley-says-the-catch-up-trade-in-energy-can-continue-and-names-its-top-picks-to-play.html',
 'https://www.cnbc.com/2024/03/29/investors-focused-overwhelmingly-on-bitcoin-over-other-crypto-says-blackrock.html',
 'https://www.cnbc.com/2024/03/29/the-frenzy-continues-researcher-names-3-new-signs-of-an-ai-bubble-amid-nvidia-hype.html',
 'https://www.cnbc.com/2024/03/28/wall-street-could-see-another-good-quarter-after-strong-start-to-2024.html',
 'https://www.cnbc.com/2024/03/29/russia-launches-barrage-of-99-drones-and-missiles-on-ukraines-energy-system-officials-say.html',
 'https://www.cnbc.com/2024/03/28/russia-knew-of-terror-attack-plot-ukraines-military-spy-chief-says.html',
 'https://www.cnbc.com/2024/03/28/ukraine-war-live-updates-latest-news-on-russia-and-the-war-in-ukraine.html',
 'https://www.cnbc.com/2024/03/27/russia-claims-west-ukraine-behind-moscow-attack-but-has-no-evidence.html',
 'https://www.cnbc.com/2024/03/27/ukraine-war-live-updates-latest-news-on-russia-and-the-war-in-ukraine.html',
 'https://www.cnbc.com/video/2024/03/26/nikolaj-coster-waldau-on-the-undpas-aweather-kidsa-climate-action-campaign.html',
 'https://www.cnbc.com/2024/03/26/natural-hydrogen-a-new-gold-rush-for-a-potential-clean-energy-source.html',
 'https://www.cnbc.com/2024/03/19/earth-on-the-brink-of-a-key-warming-threshold-after-chart-busting-year.html',
 'https://www.cnbc.com/2024/03/18/modular-housing-a-century-old-sustainable-housing-idea-is-struggling.html',
 'https://www.cnbc.com/2024/03/11/paris-has-hiked-parking-charges-on-suvs-now-cities-like-london-are-taking-note.html',
 'https://www.cnbc.com/2024/03/29/la-dolce-vita-orient-express-train-what-a-one-night-journey-costs.html',
 'https://www.cnbc.com/2024/03/28/what-are-the-best-restaurants-in-asia-here-the-top-50-for-2024-.html',
 'https://www.cnbc.com/2024/03/22/quiet-luxury-vacations-where-and-how-the-wealthy-travel-is-changing-.html',
 'https://www.cnbc.com/2024/03/21/passport-free-travel-in-singapore-is-here-but-not-where-you-may-think.html',
 'https://www.cnbc.com/2024/03/15/japans-fukui-prefecture-what-to-do-along-new-bullet-train-route.html',
 'https://www.cnbc.com/2024/03/29/richest-retirement-towns-us-gobankingrates.html',
 'https://www.cnbc.com/2024/03/29/women-make-up-1percent-of-construction-ceoshow-this-30-year-old-became-one.html',
 'https://www.cnbc.com/2024/03/29/ltk-founder-amber-venz-box-top-advice-for-inexperienced-entrepreneurs.html',
 'https://www.cnbc.com/2024/03/29/the-most-in-demand-remote-jobs-paying-over-100000-that-companies-are-hiring-for-right-now.html',
 'https://www.cnbc.com/2024/03/07/ultimate-guide-to-earning-passive-income-online.html',
 'https://www.cnbc.com/video/2024/03/28/evtols-how-flying-cars-are-becoming-reality.html',
 'https://www.cnbc.com/video/2024/02/29/how-chinas-property-bubble-burst.html',
 'https://www.cnbc.com/video/2024/01/15/what-is-the-world-economic-forum.html',
 'https://www.cnbc.com/video/2022/07/04/the-quad-expands-beyond-naval-military-exercises-and-china-watches.html',
 'https://www.cnbc.com/video/2021/12/16/why-a-coup-in-guinea-was-felt-around-the-world.html']

In [347]:
# Extracting news date-
date = []
for i in link:
    x=re.findall('\d{4}/\d{2}/\d{2}',i)
    date.append(x)
date

[['2024/03/28'],
 ['2024/03/27'],
 ['2024/03/28'],
 ['2024/03/28'],
 ['2024/03/29'],
 ['2024/03/29'],
 ['2024/03/29'],
 ['2024/03/29'],
 ['2024/03/28'],
 ['2024/03/29'],
 ['2024/03/28'],
 ['2024/03/28'],
 ['2024/03/27'],
 ['2024/03/27'],
 ['2024/03/26'],
 ['2024/03/26'],
 ['2024/03/19'],
 ['2024/03/18'],
 ['2024/03/11'],
 ['2024/03/29'],
 ['2024/03/28'],
 ['2024/03/22'],
 ['2024/03/21'],
 ['2024/03/15'],
 ['2024/03/29'],
 ['2024/03/29'],
 ['2024/03/29'],
 ['2024/03/29'],
 ['2024/03/07'],
 ['2024/03/28'],
 ['2024/02/29'],
 ['2024/01/15'],
 ['2022/07/04'],
 ['2021/12/16']]

In [357]:
#Creating dataframe-
df7=pd.DataFrame({'News heading':headings,'News Date':date,'News link':link})
df7

,News heading,News Date,News link
0,Wall Street could be in for another good quart...,[2024/03/28],https://www.cnbc.com/2024/03/28/wall-street-co...
1,"S&P 500 closes at a fresh record, posts strong...",[2024/03/27],https://www.cnbc.com/2024/03/27/stock-market-t...
2,The S&P 500 is about to wrap the quarter with ...,[2024/03/28],https://www.cnbc.com/2024/03/28/the-sp-500-is-...
3,How this bull market could unravel and what to...,[2024/03/28],https://www.cnbc.com/2024/03/28/how-this-bull-...
4,This winning sector could see even more upside...,[2024/03/29],https://www.cnbc.com/2024/03/29/this-sector-no...
5,Morgan Stanley names its top picks for the cat...,[2024/03/29],https://www.cnbc.com/2024/03/29/morgan-stanley...
6,Investors focused 'overwhelmingly' on bitcoin ...,[2024/03/29],https://www.cnbc.com/2024/03/29/investors-focu...
7,‘The frenzy continues’: Researcher names signs...,[2024/03/29],https://www.cnbc.com/2024/03/29/the-frenzy-con...
8,Wall Street could see another good quarter aft...,[2024/03/28],https://www.cnbc.com/2024/03/28/wall-street-co...
9,Russia launches barrage of 99 drones and missi...,[2024/03/29],https://www.cnbc.com/2024/03/29/russia-launche...
10,Russia knew of terrorist attack plot weeks ago...,[2024/03/28],https://www.cnbc.com/2024/03/28/russia-knew-of...
11,Putin says NATO won't be attacked but F-16s wi...,[2024/03/28],https://www.cnbc.com/2024/03/28/ukraine-war-li...
12,"Russia claims the West, Kyiv ordered the Mosco...",[2024/03/27],https://www.cnbc.com/2024/03/27/russia-claims-...
13,Russia says it's 'hard to believe' Islamic Sta...,[2024/03/27],https://www.cnbc.com/2024/03/27/ukraine-war-li...
14,Nikolaj Coster-Waldau on the UN’s 'Weather Kid...,[2024/03/26],https://www.cnbc.com/video/2024/03/26/nikolaj-...
15,Hopes for buried hydrogen’s clean energy poten...,[2024/03/26],https://www.cnbc.com/2024/03/26/natural-hydrog...
16,Earth on the brink of critical warming thresho...,[2024/03/19],https://www.cnbc.com/2024/03/19/earth-on-the-b...
17,"Modular construction, seen as a solution to ho...",[2024/03/18],https://www.cnbc.com/2024/03/18/modular-housin...
18,Paris has hiked parking charges on SUVs. Now c...,[2024/03/11],https://www.cnbc.com/2024/03/11/paris-has-hike...
19,Italy's new 'Orient Express' isn't running yet...,[2024/03/29],https://www.cnbc.com/2024/03/29/la-dolce-vita-...
20,A new Japanese restaurant tops 'Asia's 50 Best...,[2024/03/28],https://www.cnbc.com/2024/03/28/what-are-the-b...
21,"'Quiet luxury' was once about fashion, but now...",[2024/03/22],https://www.cnbc.com/2024/03/22/quiet-luxury-v...
22,Passport-free travel in Singapore is here — bu...,[2024/03/21],https://www.cnbc.com/2024/03/21/passport-free-...
23,Japan launches bullet train service to a regio...,[2024/03/15],https://www.cnbc.com/2024/03/15/japans-fukui-p...
24,"California, not Florida, is home to the riches...",[2024/03/29],https://www.cnbc.com/2024/03/29/richest-retire...
25,Just 1% of construction CEOs are women—how thi...,[2024/03/29],https://www.cnbc.com/2024/03/29/women-make-up-...
26,How a 36-year-old with 'little experience' bui...,[2024/03/29],https://www.cnbc.com/2024/03/29/ltk-founder-am...
27,"10 in-demand remote jobs paying over $100,000 ...",[2024/03/29],https://www.cnbc.com/2024/03/29/the-most-in-de...
28,The ultimate guide to earning passive income o...,[2024/03/07],https://www.cnbc.com/2024/03/07/ultimate-guide...
29,eVTOLS: How flying cars are becoming reality,[2024/03/28],https://www.cnbc.com/video/2024/03/28/evtols-h...
30,How China's property bubble burst,[2024/02/29],https://www.cnbc.com/video/2024/02/29/how-chin...
31,What is the World Economic Forum?,[2024/01/15],https://www.cnbc.com/video/2024/01/15/what-is-...
32,The Quad is going beyond military exercises — ...,[2022/07/04],https://www.cnbc.com/video/2022/07/04/the-quad...
33,Why a coup in Guinea was felt around the world,[2021/12/16],https://www.cnbc.com/video/2021/12/16/why-a-co...

### 8) Please visit https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloaded- articles/ and scrap- a) Paper title b) date c) Author

In [358]:
#Get request sent to website-
page8=requests.get('https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloaded-articles/')
page8

In [359]:
#Create BeautifulSoup Object-
soup8=BeautifulSoup(page8.content)

In [362]:
#Extracting Paper Title-
title=[]
for i in soup8.find_all('h2',class_="h5 article-title"):
    title.append(i.text.strip())
title

['Implementation of artificial intelligence in agriculture for optimisation of irrigation and application of pesticides and herbicides',
 'A comprehensive review on automation in agriculture using artificial intelligence',
 'Review of agricultural IoT technology',
 'Automation and digitization of agriculture using artificial intelligence and internet of things',
 'Real-time hyperspectral imaging for the in-field estimation of strawberry ripeness with deep learning',
 'Applications of electronic nose (e-nose) and electronic tongue (e-tongue) in food quality-related properties determination: A review',
 'Fruit ripeness classification: A survey',
 'A review of imaging techniques for plant disease detection',
 'Deep learning based computer vision approaches for smart agricultural applications',
 'Comparison of CNN-based deep learning architectures for rice diseases classification',
 'Transfer Learning for Multi-Crop Leaf Disease Image Classification using Convolutional Neural Network VGG',
 'DeepRice: A deep learning and deep feature based classification of Rice leaf disease subtypes',
 'Plant disease detection using hybrid model based on convolutional autoencoder and convolutional neural network',
 'How artificial intelligence uses to achieve the agriculture sustainability: Systematic review',
 'Deep convolutional neural network models for weed detection in polyhouse grown bell peppers',
 'Machine learning in nutrient management: A review',
 'Machine learning for weed–plant discrimination in agriculture 5.0: An in-depth review',
 'A systematic review of machine learning techniques for cattle identification: Datasets, methods and future directions',
 'Examining the interplay between artificial intelligence and the agri-food industry',
 'A review on computer vision systems in monitoring of poultry: A welfare perspective',
 'Artificial cognition for applications in smart agriculture: A comprehensive review',
 'Explainable artificial intelligence and interpretable machine learning for agricultural data analysis',
 'Vision Intelligence for Smart Sheep Farming: Applying Ensemble Learning to Detect Sheep Breeds',
 'Crop diagnostic system: A robust disease detection and management system for leafy green crops grown in an aquaponics facility',
 'Blockchain: A new safeguard for agri-foods']

In [366]:
#Extracting Date-
date=[]
for i in soup8.find_all('p',class_="article-date"):
    date.append(i.text)
date

['2020',
 'June 2019',
 '2022',
 '2021',
 '2020',
 '2020',
 'March 2023',
 '2020',
 '2022',
 'September 2023',
 '2022',
 'March 2024',
 '2021',
 'June 2023',
 '2022',
 'September 2023',
 'December 2023',
 '2022',
 '2022',
 '2020',
 '2020',
 '2022',
 'March 2024',
 'December 2023',
 '2020']

In [370]:
#Extracting Paper Author-
author=[]
for i in soup8.find_all('p',class_="article-authors"):
    author.append(i.text.strip())
author

['Tanha Talaviya |  Dhara Shah |  Nivedita Patel |  Hiteshri Yagnik |  Manan Shah',
 'Kirtan Jha |  Aalap Doshi |  Poojan Patel |  Manan Shah',
 'Jinyuan Xu |  Baoxing Gu |  Guangzhao Tian',
 'A. Subeesh |  C.R. Mehta',
 'Zongmei Gao |  Yuanyuan Shao |  Guantao Xuan |  Yongxian Wang |  Yi Liu |  Xiang Han',
 'Juzhong Tan |  Jie Xu',
 'Matteo Rizzo |  Matteo Marcuzzo |  Alessandro Zangari |  Andrea Gasparetto |  Andrea Albarelli',
 'Vijai Singh |  Namita Sharma |  Shikha Singh',
 'V.G. Dhanya |  A. Subeesh |  N.L. Kushwaha |  Dinesh Kumar Vishwakarma |  T. Nagesh Kumar |  G. Ritika |  A.N. Singh',
 'Md Taimur Ahad |  Yan Li |  Bo Song |  Touhid Bhuiyan',
 'Ananda S. Paymode |  Vandana B. Malode',
 'P. Isaac Ritharson |  Kumudha Raimond |  X. Anitha Mary |  Jennifer Eunice Robert |  Andrew J',
 'Punam Bedi |  Pushkar Gole',
 'Vilani Sachithra |  L.D.C.S. Subhashini',
 'A. Subeesh |  S. Bhole |  K. Singh |  N.S. Chandel |  Y.A. Rajwade |  K.V.R. Rao |  S.P. Kumar |  D. Jat',
 'Oumnia Ennaji |  Leonardus Vergütz |  Achraf El Allali',
 'Filbert H. Juwono |  W.K. Wong |  Seema Verma |  Neha Shekhawat |  Basil Andy Lease |  Catur Apriono',
 'Md Ekramul Hossain |  Muhammad Ashad Kabir |  Lihong Zheng |  Dave L. Swain |  Shawn McGrath |  Jonathan Medway',
 'Abderahman Rejeb |  Karim Rejeb |  Suhaiza Zailani |  John G. Keogh |  Andrea Appolloni',
 'Cedric Okinda |  Innocent Nyalala |  Tchalla Korohou |  Celestine Okinda |  Jintao Wang |  Tracy Achieng |  Patrick Wamalwa |  Tai Mang |  Mingxia Shen',
 'Misbah Pathan |  Nivedita Patel |  Hiteshri Yagnik |  Manan Shah',
 'Masahiro Ryo',
 'Galib Muhammad Shahriar Himel |  Md. Masudul Islam |  Mijanur Rahaman',
 'R. Abbasi |  P. Martinez |  R. Ahmad',
 'Jie Xu |  Shuang Guo |  David Xie |  Yaxuan Yan']

In [373]:
#Creating dataframe-
df8=pd.DataFrame({'Paper_title':title,'Date':date,'Author':author})
df8

,Paper_title,Date,Author
0,Implementation of artificial intelligence in a...,2020,Tanha Talaviya | Dhara Shah | Nivedita Patel...
1,A comprehensive review on automation in agricu...,June 2019,Kirtan Jha | Aalap Doshi | Poojan Patel | M...
2,Review of agricultural IoT technology,2022,Jinyuan Xu | Baoxing Gu | Guangzhao Tian
3,Automation and digitization of agriculture usi...,2021,A. Subeesh | C.R. Mehta
4,Real-time hyperspectral imaging for the in-fie...,2020,Zongmei Gao | Yuanyuan Shao | Guantao Xuan |...
5,Applications of electronic nose (e-nose) and e...,2020,Juzhong Tan | Jie Xu
6,Fruit ripeness classification: A survey,March 2023,Matteo Rizzo | Matteo Marcuzzo | Alessandro ...
7,A review of imaging techniques for plant disea...,2020,Vijai Singh | Namita Sharma | Shikha Singh
8,Deep learning based computer vision approaches...,2022,V.G. Dhanya | A. Subeesh | N.L. Kushwaha | ...
9,Comparison of CNN-based deep learning architec...,September 2023,Md Taimur Ahad | Yan Li | Bo Song | Touhid ...
10,Transfer Learning for Multi-Crop Leaf Disease ...,2022,Ananda S. Paymode | Vandana B. Malode
11,DeepRice: A deep learning and deep feature bas...,March 2024,P. Isaac Ritharson | Kumudha Raimond | X. An...
12,Plant disease detection using hybrid model bas...,2021,Punam Bedi | Pushkar Gole
13,How artificial intelligence uses to achieve th...,June 2023,Vilani Sachithra | L.D.C.S. Subhashini
14,Deep convolutional neural network models for w...,2022,A. Subeesh | S. Bhole | K. Singh | N.S. Cha...
15,Machine learning in nutrient management: A review,September 2023,Oumnia Ennaji | Leonardus Vergütz | Achraf E...
16,Machine learning for weed–plant discrimination...,December 2023,Filbert H. Juwono | W.K. Wong | Seema Verma ...
17,A systematic review of machine learning techni...,2022,Md Ekramul Hossain | Muhammad Ashad Kabir | ...
18,Examining the interplay between artificial int...,2022,Abderahman Rejeb | Karim Rejeb | Suhaiza Zai...
19,A review on computer vision systems in monitor...,2020,Cedric Okinda | Innocent Nyalala | Tchalla K...
20,Artificial cognition for applications in smart...,2020,Misbah Pathan | Nivedita Patel | Hiteshri Ya...
21,Explainable artificial intelligence and interp...,2022,Masahiro Ryo
22,Vision Intelligence for Smart Sheep Farming: A...,March 2024,Galib Muhammad Shahriar Himel | Md. Masudul I...
23,Crop diagnostic system: A robust disease detec...,December 2023,R. Abbasi | P. Martinez | R. Ahmad
24,Blockchain: A new safeguard for agri-foods,2020,Jie Xu | Shuang Guo | David Xie | Yaxuan Yan

In [376]:
#Replacing "|" in author name with ","-
df8['Author']=df8['Author'].str.replace('|',',',regex=True)

In [377]:
df8

,Paper_title,Date,Author
0,Implementation of artificial intelligence in a...,2020,"Tanha Talaviya , Dhara Shah , Nivedita Patel..."
1,A comprehensive review on automation in agricu...,June 2019,"Kirtan Jha , Aalap Doshi , Poojan Patel , M..."
2,Review of agricultural IoT technology,2022,"Jinyuan Xu , Baoxing Gu , Guangzhao Tian"
3,Automation and digitization of agriculture usi...,2021,"A. Subeesh , C.R. Mehta"
4,Real-time hyperspectral imaging for the in-fie...,2020,"Zongmei Gao , Yuanyuan Shao , Guantao Xuan ,..."
5,Applications of electronic nose (e-nose) and e...,2020,"Juzhong Tan , Jie Xu"
6,Fruit ripeness classification: A survey,March 2023,"Matteo Rizzo , Matteo Marcuzzo , Alessandro ..."
7,A review of imaging techniques for plant disea...,2020,"Vijai Singh , Namita Sharma , Shikha Singh"
8,Deep learning based computer vision approaches...,2022,"V.G. Dhanya , A. Subeesh , N.L. Kushwaha , ..."
9,Comparison of CNN-based deep learning architec...,September 2023,"Md Taimur Ahad , Yan Li , Bo Song , Touhid ..."
10,Transfer Learning for Multi-Crop Leaf Disease ...,2022,"Ananda S. Paymode , Vandana B. Malode"
11,DeepRice: A deep learning and deep feature bas...,March 2024,"P. Isaac Ritharson , Kumudha Raimond , X. An..."
12,Plant disease detection using hybrid model bas...,2021,"Punam Bedi , Pushkar Gole"
13,How artificial intelligence uses to achieve th...,June 2023,"Vilani Sachithra , L.D.C.S. Subhashini"
14,Deep convolutional neural network models for w...,2022,"A. Subeesh , S. Bhole , K. Singh , N.S. Cha..."
15,Machine learning in nutrient management: A review,September 2023,"Oumnia Ennaji , Leonardus Vergütz , Achraf E..."
16,Machine learning for weed–plant discrimination...,December 2023,"Filbert H. Juwono , W.K. Wong , Seema Verma ..."
17,A systematic review of machine learning techni...,2022,"Md Ekramul Hossain , Muhammad Ashad Kabir , ..."
18,Examining the interplay between artificial int...,2022,"Abderahman Rejeb , Karim Rejeb , Suhaiza Zai..."
19,A review on computer vision systems in monitor...,2020,"Cedric Okinda , Innocent Nyalala , Tchalla K..."
20,Artificial cognition for applications in smart...,2020,"Misbah Pathan , Nivedita Patel , Hiteshri Ya..."
21,Explainable artificial intelligence and interp...,2022,Masahiro Ryo
22,Vision Intelligence for Smart Sheep Farming: A...,March 2024,"Galib Muhammad Shahriar Himel , Md. Masudul I..."
23,Crop diagnostic system: A robust disease detec...,December 2023,"R. Abbasi , P. Martinez , R. Ahmad"
24,Blockchain: A new safeguard for agri-foods,2020,"Jie Xu , Shuang Guo , David Xie , Yaxuan Yan"